bughunters-mentorship/praga

students/saraceni
This PR adds Saraceni's student file, with a brief discription of him.
=> chore: add saraceni file

students/teste
Essa PR adiciona o arquivo de teste à pasta students
=> chore: add test file

students/Davi
=> chore: add Davi file

students/fabio-cesar.txt
=> chore: add fabio-cesar.txt

students/brunoAdami
=> Chore: added text file brunoAdami

students/janaina
=> chore: add file janaina

classes/turing
Add the first line
1 - Rogerio Kotsubo
=> chore: add first line

classes/turing
I edited the text file of Rogerio (the first to modify the file) to try to solve the conflict, but I don't know if it's the correct way to solve it.
=> Feat: Added text in the file

students/janaina
=> docs: correct spelling and words

classes/turing
=> modifier turing file

students/marlisson
Essa PR adiciona o arquivo marlisson à pasta students
=> chore: add marlisson file

students/Guyrlam.txt
Addition of the student description following what was requested.
=> feat:student_description

students/filipeGomes
Essa PR adiciona o arquivo filipeGomes.txt na pasta students.
=> chore: add filipe file

students/geverson-araujo.txt
=> Commit alterando a pasta students

classes/turing, students/AlvaroMF.txt
=> chore: add AlvaroMF file

classes/turing
=> chore: change text

students/Akira.txt
=> chore add Akira.txt

classes/turing
=> docs: add Guyrlam

students/Lucas Reis.txt
=> chore: add Lucas Reis.txt

students/AdrieleSantos.txt
adicionando arquivo AdrieleSantos.txt
=> chore: adicionando arquivo na branch Adriele

classes/turing
Não tive problemas com merge. Sorte? rsrsrs
=> chore: tentando resolver o desafio

students/Luiz Antônio.txt
=> Luiz antonio

classes/turing, students/AdrieleSantos.txt
=> Adri branch

students/LuizaBarbalho.txt
=> chore: add LuizaBarbalho.txt

students/VictorRaffaele
chore: add victorraffaele file to praga repository
=> chore: add file victorraffaele

students/YanVictorSN.txt
Olá, alguém pode aprovar minha PR? Obrigado!
=> chore: add YanVictorSN file

students/antoniofrancisco.txt
=> antonio francisco

classes/turing
=> chore:add Lucelia

JoaoAlexandre
=> chore: JoaoAlexandre

students/Lucelia.txt
=> chore: add Lucelia

index.html
This PR adds index.html to root directory of repository. This file will be used to test conflicts and show the use of `git rebase`.
=> feat: create index html

index.html
=> chore: modify file index.html

index.html
mudança no <p> com id:#commit-here 
adição da canção do exilio.
=> chore: change index.html paragraph #commit-here

index.html
=> chore: add something

index.html
Formatting the changes I made earlier to look prettier.
=> chore: add changes to index.html
